### ISSUE TITLE
Cascade environment and generating 32-bit ELFs

### ISSUE THREAD

**Issue by Subway2023** [comsec-group/cascade-artifacts#15]
```bash
root@0c232c964e9c:/# python3 cascade-meta/fuzzer/do_fuzzdesign.py
Traceback (most recent call last):
  File "//cascade-meta/fuzzer/do_fuzzdesign.py", line 13, in <module>
    from top.fuzzdesign import fuzzdesign
  File "/cascade-meta/fuzzer/top/fuzzdesign.py", line 7, in <module>
    from common.spike import calibrate_spikespeed
  File "/cascade-meta/fuzzer/common/spike.py", line 11, in <module>
    from params.runparams import DO_ASSERT, PATH_TO_TMP, NO_REMOVE_TMPFILES
  File "/cascade-meta/fuzzer/params/runparams.py", line 5, in <module>
    raise Exception("The Cascade environment must be sourced prior to running the Python recipes.")
Exception: The Cascade environment must be sourced prior to running the Python recipes.
```

**Comment by flaviens** [comment]
Hi Subway, as stated in the error message you have to source the cascade environnement.
You can do this by `source <path_to_cascade-meta_repo>/env.sh`.
Hope it helps!

**Comment by Subway2023** [comment]
May I ask where the generated test program (elf) is stored? I would like to use it to test other DUTs

**Comment by Subway2023** [comment]
Could you please tell me how to generate a 32-bit ELF using this tool?

**Comment by flaviens** [comment]
[This script](https://github.com/cascade-artifacts-designs/cascade-meta/blob/master/fuzzer/do_genmanyelfs.py) most likely does exactly what you would like.
You can change 'rocket' in the script with a design of equivalent ISA/extensions as your design, if there is some in the cascade corpus of designs, for example kronos.

**Comment by Subway2023** [comment]
Hi, flaviens, thank you for your previous response, which successfully generated the 32-bit ELF. 

I have one more question: How can I restrict the address range that the generated program can access? I tried running the program generated by Cascade in zkvm, but zkvm has a maximum address limit and the following error occurred:
```
thread 'main' panicked at host/src/main.rs:93:64:
called `Result::unwrap()` on an `Err` value: Address [0x80000000] exceeds maximum address for guest programs [0x0c000000]
```

**Comment by flaviens** [comment]
Hi @Subway2023 , at the moment Cascade only produces programs located at `0x80000000`. This is usually a very soft restriction. Changing this would require a little bit of work but has not yet been done. Happy to help if you'd like to enhance this.
